name: Deploy on commit to main

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted # Runs on YOUR computer
    steps:
      - uses: actions/checkout@v3
      - name: Run commands
        run: |
          cd ~/my_project
          docker compose pull
          docker compose up -d --build
